sections:
  magento_information:
    display: 'Magento Information'
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          visibility: read_only
          validate:
            - required
      -
        handle: sku
        field:
          input_type: text
          antlers: false
          display: Sku
          type: text
          icon: text
          listable: true
          instructions_position: above
          visibility: read_only
      -
        handle: store
        field:
          input_type: text
          antlers: false
          display: Store
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: read_only
      -
        handle: id
        field:
          input_type: text
          antlers: false
          display: id
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: read_only
          validate:
            - 'unique_entry_value:{collection},{id},{site}'
  content:
    display: Content
    fields: {  }
title: Products
